# OpenEXR dependency
# https://github.com/AcademySoftwareFoundation/openexr
#
# Output target: LibOpenEXR
#


include(${CMAKE_SOURCE_DIR}/cmake/external_project_common.cmake)

include(${CMAKE_SOURCE_DIR}/cmake/dependency.openjph.cmake)

find_package(Git REQUIRED) # needed by OpenEXR

ExternalProject_Add(EXR
    PREFIX ${CMAKE_BINARY_DIR}/openexr
    URL "https://github.com/AcademySoftwareFoundation/openexr/archive/refs/tags/v3.4.4.zip"
    URL_MD5 "23a4152db8b04ad484e9e1dd6638a662"
    DOWNLOAD_DIR "${CMAKE_SOURCE_DIR}/dependencies/openexr"
    SOURCE_DIR "${EXTERNALPROJECT_SOURCE_PREFIX}/dependencies/openexr/source"
    BINARY_DIR "${CMAKE_BINARY_DIR}/openexr/build"
    INSTALL_DIR "${CMAKE_BINARY_DIR}/openexr/install"
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    UPDATE_COMMAND ""
    PATCH_COMMAND ""
    BUILD_COMMAND ${BUILD_COMMAND_FOR_TARGET} -t OpenEXR
    CMAKE_ARGS ${CMAKE_BUILD_TYPE_ARG} "-DOPENEXR_IS_SUBPROJECT=ON" "-DOPENEXR_FORCE_INTERNAL_IMATH=ON" "-DOPENEXR_FORCE_INTERNAL_DEFLATE=ON" "-DOPENEXR_INSTALL=ON"
        "-DOPENEXR_INSTALL_TOOLS=OFF" "-DOPENEXR_INSTALL_EXAMPLES=OFF" "-DOPENEXR_INSTALL_PKG_CONFIG=OFF" "-DOPENEXR_BUILD_TOOLS=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DBUILD_TESTING=OFF"
        "-DOPENEXR_LIB_SUFFIX=" "-DGIT_EXECUTABLE:PATH=${GIT_EXECUTABLE}" "-DCMAKE_C_FLAGS:STRING=${ZERO_WARNINGS_FLAG}" "-DCMAKE_CXX_FLAGS:STRING=${ZERO_WARNINGS_FLAG}"
        "-DIMATH_LIB_SUFFIX=" "-Dopenjph_ROOT=${OPENJPH_ROOT}" "-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}/openexr/install"
    EXCLUDE_FROM_ALL
    DEPENDS OPENJPH
)

ExternalProject_Get_Property(EXR INSTALL_DIR)

set(OPENJPH_VERSION_SUFFIX ".0.24")

add_library(LibOpenEXR INTERFACE)
add_dependencies(LibOpenEXR EXR)
link_library_path2(LibOpenEXR ${INSTALL_DIR}/lib ${CMAKE_STATIC_LIBRARY_PREFIX}OpenEXR${CMAKE_STATIC_LIBRARY_SUFFIX} ${CMAKE_STATIC_LIBRARY_PREFIX}OpenEXR_d${CMAKE_STATIC_LIBRARY_SUFFIX})
link_library_path2(LibOpenEXR ${INSTALL_DIR}/lib ${CMAKE_STATIC_LIBRARY_PREFIX}OpenEXRCore${CMAKE_STATIC_LIBRARY_SUFFIX} ${CMAKE_STATIC_LIBRARY_PREFIX}OpenEXRCore_d${CMAKE_STATIC_LIBRARY_SUFFIX})
link_library_path2(LibOpenEXR ${INSTALL_DIR}/lib ${CMAKE_STATIC_LIBRARY_PREFIX}Imath${CMAKE_STATIC_LIBRARY_SUFFIX} ${CMAKE_STATIC_LIBRARY_PREFIX}Imath_d${CMAKE_STATIC_LIBRARY_SUFFIX})
link_library_path2(LibOpenEXR ${INSTALL_DIR}/lib ${CMAKE_STATIC_LIBRARY_PREFIX}Iex${CMAKE_STATIC_LIBRARY_SUFFIX} ${CMAKE_STATIC_LIBRARY_PREFIX}Iex_d${CMAKE_STATIC_LIBRARY_SUFFIX})
link_library_path2(LibOpenEXR ${INSTALL_DIR}/lib ${CMAKE_STATIC_LIBRARY_PREFIX}IlmThread${CMAKE_STATIC_LIBRARY_SUFFIX} ${CMAKE_STATIC_LIBRARY_PREFIX}IlmThread_d${CMAKE_STATIC_LIBRARY_SUFFIX})
target_include_directories(LibOpenEXR INTERFACE ${INSTALL_DIR}/include ${INSTALL_DIR}/include/Imath ${INSTALL_DIR}/include/OpenEXR)
target_link_libraries(LibOpenEXR INTERFACE LibOpenJPH)
set_property(TARGET EXR PROPERTY FOLDER "Dependencies")

unset(INSTALL_DIR)
