# libaom dependency, part of libheif
# https://aomedia.googlesource.com/aom
#
# Output targets: LibAOM


include(${EXTERNALPROJECT_INCLUDE_DIR}/external_project_common.cmake)

# Fix AOM configuraion for cross-compilation
set(AOM_TARGET_CPU_FLAG "")
if (ANDROID OR CMAKE_VS_PLATFORM_NAME STREQUAL "ARM64")
    set(AOM_TARGET_CPU_FLAG "-DAOM_TARGET_CPU=aarch64")
endif()

ExternalProject_Add(AOM
    PREFIX ${EXTERNALPROJECT_BINARY_ROOT}/libaom
    GIT_REPOSITORY https://aomedia.googlesource.com/aom
    GIT_TAG v3.15.1
    GIT_SHALLOW TRUE
    DOWNLOAD_DIR "${EXTERNALPROJECT_SOURCE_ROOT}/libaom"
    SOURCE_DIR "${EXTERNALPROJECT_SOURCE_PREFIX}/libaom/source"
    BINARY_DIR "${EXTERNALPROJECT_BINARY_ROOT}/libaom/build"
    INSTALL_DIR "${EXTERNALPROJECT_BINARY_ROOT}/libaom/install"
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    UPDATE_COMMAND ""
    PATCH_COMMAND ""
    BUILD_COMMAND ${BUILD_COMMAND_FOR_TARGET} -t aom
    INSTALL_COMMAND ${BUILD_COMMAND_FOR_TARGET} -t install
    CMAKE_ARGS ${EXTERNALPROJECT_CMAKE_ARGS} ${AOM_TARGET_CPU_FLAG} "-DBUILD_SHARED_LIBS=OFF"
        "-DENABLE_APPS=0" "-DENABLE_DOCS=0" "-DENABLE_EXAMPLES=0" "-DENABLE_TESTDATA=0" "-DENABLE_TESTS=0" "-DENABLE_TOOLS=0"
        "-DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS} ${ZERO_WARNINGS_FLAG}" "-DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS} ${ZERO_WARNINGS_FLAG}"
        "-DCMAKE_INSTALL_PREFIX:PATH=${EXTERNALPROJECT_BINARY_ROOT}/libaom/install" "-DCMAKE_DEBUG_POSTFIX="
    EXCLUDE_FROM_ALL
)

ExternalProject_Get_Property(AOM INSTALL_DIR)

set_property(TARGET AOM PROPERTY FOLDER "Dependencies")

set(LIBAOM_INCLUDE_DIRS ${INSTALL_DIR}/include)
set(LIBAOM_LINK_DIRS ${INSTALL_DIR}/lib)
set(LIBAOM_LIBRARY aom)
set(LIBAOM_ROOT ${INSTALL_DIR}/lib/cmake/AOM)

unset(INSTALL_DIR)

